### PR TITLE
added license moved recipe into repo

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 I thought you had already a fix for the test not passing? Did it not get merged into master? Do you mind tsking a look? Thx.

**Comment by dnadeau4** [comment]
I did not figure out why the results are so different now.  
Something changed in numpy and npy.allclose() failed.

A)
-0.49048128724098206
B)
-0.4904812315217419

**Comment by doutriaux1** [comment]
ok i will force numpy<15 then

**Comment by doutriaux1** [comment]
@dnadeau4 so apparently the error was introduced by numpy 1.14.6, let's try to remember.

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 as an FYI this happened (right now) this morning:
```
conda create -n cdat80cmor333nclnco -c conda-forge -c cdat cdat 'python<=3'
...
    netcdf-fortran:                     4.4.4-7                 conda-forge
    notebook:                           5.7.0-py27_1000         conda-forge
    numpy:                              1.15.0-py27h1b885b7_0              
    numpy-base:                         1.15.0-py27h3dfced4_0              
    numpydoc:                           0.8.0-py_1              conda-forge
    openssl:                            1.0.2p-h470a237_1       conda-forge
...
```

Is the `numpy 1.15.0` bad?

**Comment by doutriaux1** [comment]
genutil test suite gives different answers since 1.14.6. @dnadeau4 is looking into this

**Comment by durack1** [comment]
@doutriaux1 I had to reinstall conda this morning (ocean problems persisted, so start again), and I am getting the following:
```
durack1@oceanonly:[~]:[10547]> conda create -n cdat80py2 -c conda-forge -c cdat cdat 'python<=3'
Solving environment: done                                                                       
## Package Plan ##
  environment location: /export/durack1/anaconda2/envs/cdat80py2
  added / updated specs: 
    - cdat               
    - python[version='<=3']
The following NEW packages will be INSTALLED:
...
    cdat:                               8.0-0                   cdat       
    cdat_info:                          8.0-py27_0              conda-forge
    cdms2:                              3.0.1-py27h6091dcd_1    conda-forge
    cdp:                                1.3.5-py_0              conda-forge
    cdtime:                             3.0-py27h6091dcd_1      conda-forge
    cdutil:                             8.0-py27_1              conda-forge
...
    genutil:                            8.0-py27_1              conda-forge
...
    numpy:                              1.15.0-py27h1b885b7_0              
    numpy-base:                         1.15.0-py27h3dfced4_0              
    numpydoc:                           0.8.0-py_1              conda-forge
...
```

Is this going to be bad? Should I force numpy version <1.15?

**Comment by durack1** [comment]
A solution for this while #26 is unresolved is to use:
```
conda create -n cdat80py2 -c conda-forge -c cdat cdat 'python<=3' 'numpy<1.14.6'
```

**Comment by dnadeau4** [comment]
@durack1 do you have similar issue with statistical in genutil.  The difference is about (1e7) and the epsilon is (1e8)  I investigated it, but could not find what library change is numpy.  I think it might be openblas/lapack kind of issue.

**Comment by durack1** [comment]
@dnadeau4 I was just recreating environments and noted this problem, so am trying to avoid even small errors creeping into my calculations.. FYI, there are a number of numpy libraries, so `numpy` and `numpy-base` and I have seen cases where the `numpy-base` has a different version, which might cause problems, dunno?

**Pull request merged**
